import Mathlib
/-! Question:
14. Find a set of generators for $\mathbb{Z}$.
-/

example : AddSubgroup.zmultiples (1 : ℤ) = ⊤ := by
  -- By definition, for a given element $n$ of $\Z$, we prove as follow that it can be generated by $1$.
  ext z
  -- Note that $n = \sum_{i = 1}^{n} 1$, and this $n$ is arbitrary, we conclude that $1$ is the generator of $\Z$.
  simpa only [AddSubgroup.mem_top, iff_true] using ⟨z, zsmul_int_one z⟩

/-! Informal proof:
By definition, for a given element $n$ of $\Z$, we prove as follow that it can be generated by $1$.
Note that $n = \sum_{i = 1}^{n} 1$, and this $n$ is arbitrary, we conclude that $1$ is the generator of $\Z$.
-/
