import Mathlib
/-! Question:
A subgroup $T$ of a group $W$ is called characteristic if $\varphi(T) \subset T$ for all automorphisms, $\varphi$, of $W$. Prove that:
$M, N$ characteristic in $G$ implies that $M N$ is characteristic in $G$.
-/

open Set

/-- if M N are characteristic subgroups of G, then so is MN. clearly any characteristic subgroups are normal, so the subgroup MN of G is exactly the subgroup generated by M and N, that is, $ MN = \langle M \cup N \rangle $ -/
theorem chargroup {G : Type*} [Group G] {M N : Subgroup G} (charM : Subgroup.Characteristic M) (charN : Subgroup.Characteristic N) : Subgroup.Characteristic (Subgroup.closure (M.carrier ∪ N.carrier)) := by
  -- let $ f : G \cong G $. We use subgroup closure induction to prove that $ \forall x \in MN, f x \in MN $
  refine Subgroup.characteristic_iff_map_le.mpr ?_
  intro f
  refine le_iff_subset.mpr ?char.a
  intro y ⟨x, ⟨h1, h2⟩⟩
  -- let $ p := \forall a : G, \forall ha : a \in \langle M \cup N \rangle, f a \in \langle M \cup N \rangle $. We prove that $ p $ holds for all $ a \in G $ by subgroup closure induction
  let p : (a : G) → a ∈ Subgroup.closure (M.carrier ∪ N.carrier) → Prop := by
    intro a _
    exact f a ∈ (Subgroup.closure (M.carrier ∪ N.carrier)).carrier
  -- base case: $ p x hx $ holds for all $ x : G $, $ hx : x \in M.carrier \cup N.carrier $, which means if $ x \in M \cup N $, then $ f x \in MN $
  have ind1 : ∀ x (hx : x ∈ M.carrier ∪ N.carrier), p x (Subgroup.subset_closure hx) := by
    intro a ha
    rcases ha with haM | haN
    · -- if $ a \in M $, then $ f a \in MN $
      let H := Subgroup.characteristic_iff_map_le.mp charM f
      -- $ f a \in f(M) $
      have H1 : f a ∈ image f M.carrier := by exact mem_image_of_mem (⇑f) haM
      -- $ f a \in M \cup N $
      have H2 : f a ∈ (M.carrier ∪ N.carrier) := by exact mem_union_left N.carrier (H H1)
      -- $ M \cup N \subseteq MN $
      have H3 : (M.carrier ∪ N.carrier) ⊆ (Subgroup.closure (M.carrier ∪ N.carrier)) := by exact Subgroup.subset_closure
      -- $ f a \in MN $
      have H5 : f a ∈ (Subgroup.closure (M.carrier ∪ N.carrier)).carrier := by exact H3 H2
      dsimp [p]
      exact H5
    · -- if $ a \in N $, then $ f a \in MN $
      let H := Subgroup.characteristic_iff_map_le.mp charN f
      -- $ f a \in f(N) $
      have H1 : f a ∈ image f N.carrier := by exact mem_image_of_mem (⇑f) haN
      -- $ f a \in M \cup N $
      have H2 : f a ∈ (M.carrier ∪ N.carrier) := by exact mem_union_right M.carrier (H H1)
      -- $ M \cup N \subseteq MN $
      have H3 : (M.carrier ∪ N.carrier) ⊆ (Subgroup.closure (M.carrier ∪ N.carrier)) := by exact Subgroup.subset_closure
      -- $ f a \in MN $
      have H5 : f a ∈ (Subgroup.closure (M.carrier ∪ N.carrier)).carrier := by exact H3 H2
      dsimp [p]
      exact H5
  -- case of one, $ p 1 $ holds for all $ 1 \in G $, which means $ f 1 \in MN $
  have ind2 : p 1 (Subgroup.one_mem _) := by
    dsimp [p]
    rw [MulEquiv.map_one f]
    exact (Subgroup.closure (M.carrier ∪ N.carrier)).one_mem'
  -- case of multiplication, $ p a ha $ and $ p b hb $ holds for all $ a, b : G $, $ ha : a \in M.carrier \cup N.carrier $, $ hb : b \in M.carrier \cup N.carrier $, which means $ f a $ and $ f b \in MN $ implies $ f a * f b \in MN $
  have ind3 : (∀ a b (ha : a ∈ Subgroup.closure (M.carrier ∪ N.carrier)) (hb : b ∈ Subgroup.closure (M.carrier ∪ N.carrier)), p a ha → p b hb → p (a * b) (Subgroup.mul_mem _ ha hb)) := by
    intro a b _ _ ha hb
    -- $ f a * f b \in MN $
    have hab : f a * f b ∈ (Subgroup.closure (M.carrier ∪ N.carrier)) := by exact (Subgroup.mul_mem_cancel_right (Subgroup.closure (M.carrier ∪ N.carrier)) hb).mpr ha
    -- $ f (a * b) \in MN $
    rw [← map_mul] at hab
    dsimp [p]
    exact hab
  -- case of inverse, $ p a^{-1} $ holds for all $ a : G $, which means $ f a \in MN $ implies $ f a^{-1} \in MN $
  have ind4 : ∀ (x : G) (hx : x ∈ Subgroup.closure (M.carrier ∪ N.carrier)), p x hx → p x⁻¹ (Subgroup.inv_mem _ hx) := by
    intro a _ ha
    -- $ f a^{-1} \in MN $
    have ha2 : (f a)⁻¹ ∈ (Subgroup.closure (M.carrier ∪ N.carrier)) := by exact (Subgroup.inv_mem_iff (Subgroup.closure (M.carrier ∪ N.carrier))).mpr ha
    rw [← map_inv] at ha2
    dsimp [p]
    exact ha2
  rw [h2.symm]
  -- apply subgroup closure induction to prove $ p $ holds for all $ x \in G $
  apply @Subgroup.closure_induction G _ (M.carrier ∪ N.carrier) p ind1 ind2 ind3 ind4
  dsimp [p]
  exact h1

/-! Informal proof:
Clearly M and N are normal subgroup of G, so MN = the subgroup closure <M, N> of  M union N.
Let f be any automorphism of G. We prove by the subgroup closure induction that if p(x) : \"x is in <M, N>\" then so is f(x):
• base case: p(x), then so is f(x)
• case of one: p(1)
• case of multiplication: if p(x) and p(y), then p(x*y)
• case of inverse: if p(x), then p(x^-1)

-/
